workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

default:
  tags: ["${GIT_RUNNER_TAG}"]

variables:
  GIT_RUNNER_TAG: "k8s-cluster-2"

.environment:
  environment: "${CI_ENVIRONMENT}"

include:
  # the order here matters: overrides from later files take precedence
  - project: sequoiadp/qa/staging
    file: staging.yml
  - project: sequoiadp/qa/staging
    file: spark.yml
  - performance.yml
