workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

variables:
  CI_RUNNER_TAG: "k8s-cluster-2"
  CI_ENVIRONMENT: "k8s-cluster-2"

default:
  tags: ["${CI_RUNNER_TAG}"]

.environment:
  environment: "${CI_ENVIRONMENT}"

include:
  # the order here matters: overrides from later files take precedence
  - project: sequoiadp/qa/staging-upstream
    file: staging.yml
    #ref: ci_pipeline
  - project: sequoiadp/qa/staging-upstream
    file: spark.yml
    #ref: ci_pipeline
  - performance.yml