workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

default:
  tags: ["${CI_RUNNER_TAG}"]

variables:
  CI_RUNNER_TAG: "k8s-cluster-1"
  CI_ENVIRONMENT: "k8s-cluster-1"
  S3A_BUCKET_NAME: ""
  S3A_ACCESS_KEY: ""
  S3A_SECRET_KEY: ""
  S3A_ENDPOINT: ""

.environment:
  environment: "${CI_ENVIRONMENT}"

include:
  # the order here matters: overrides from later files take precedence
  - project: sequoiadp/qa/staging-downstream
    file: staging.yml
  - project: sequoiadp/qa/staging-downstream
    file: spark.yml
  - performance.yml